//
// Created by lenny on 28/01/24.
//

#ifndef AUTOPILOT_FLIGHT_CONTROLLER_SOFTWARE_POSITIONMODULE_H
#define AUTOPILOT_FLIGHT_CONTROLLER_SOFTWARE_POSITIONMODULE_H

void navigationTask(void *args);

#endif //AUTOPILOT_FLIGHT_CONTROLLER_SOFTWARE_POSITIONMODULE_H
