//
// Created by lenny on 15/01/24.
//

#ifndef AUTOPILOT_FLIGHT_CONTROLLER_SOFTWARE_ALTITUDEMODULE_H
#define AUTOPILOT_FLIGHT_CONTROLLER_SOFTWARE_ALTITUDEMODULE_H

#include <cstdint>

void altitudeTask(void *args);

#endif //AUTOPILOT_FLIGHT_CONTROLLER_SOFTWARE_ALTITUDEMODULE_H
