#ifndef AUTOPILOT_FLIGHT_CONTROLLER_SOFTWARE_COMMANDERMODULE_H
#define AUTOPILOT_FLIGHT_CONTROLLER_SOFTWARE_COMMANDERMODULE_H

#include <cstdint>

void commanderTask(void *args);

#endif //AUTOPILOT_FLIGHT_CONTROLLER_SOFTWARE_COMMANDERMODULE_H