#ifndef AUTOPILOT_FLIGHT_CONTROLLER_SOFTWARE_CONTROLLERMODULE_H
#define AUTOPILOT_FLIGHT_CONTROLLER_SOFTWARE_CONTROLLERMODULE_H

#include <cstdint>

void controllerTask(void *args);

#endif //AUTOPILOT_FLIGHT_CONTROLLER_SOFTWARE_CONTROLLERMODULE_H