//
// Created by lenny on 28/01/24.
//

#ifndef AUTOPILOT_FLIGHT_CONTROLLER_SOFTWARE_MOTORSMODULE_H
#define AUTOPILOT_FLIGHT_CONTROLLER_SOFTWARE_MOTORSMODULE_H

void motorsTask(void *args);

#endif //AUTOPILOT_FLIGHT_CONTROLLER_SOFTWARE_MOTORSMODULE_H
